### PR TITLE
Fix deprecated in Nette 2.3.10

### PR DESCRIPTION
**Pull request by Trejjam**

### CODE REVIEW

**Comment by Trejjam** [comment]
Require [Nette/Forms:118](https://github.com/nette/forms/pull/118)

**Comment by fprochazka** [comment]
Thank you but I don't think this is a good way to solve it. Imho it should be conservated for Nette 2.2 and completely rewritten for Nette 2.3 so it doesn't use extension methods.

**Comment by Trejjam** [comment]
Thank you, do you have some recommendation how to implement `$form->addDynamic` without extending `Form` class? (Extending class could be problematic -> Form has'n have factory)

**Comment by fprochazka** [comment]
That is my point :) We'll have to conservate it for the people that are still using it with older Nette like 2.2.*, maybe just maybe we might make a 2.3.* compatible version, as I don't think the BC Break of deprecating the extension methods will get into 2.3.* releases. 

And then, we can rewrite it with better approach for future applications.

**Comment by fprochazka** [comment]
Thank you, merged https://github.com/Kdyby/FormsReplicator/commit/662d910af396b4253a2883c08c4440143069aab6

**Pull request closed without merging**
